name: SQL Lint using SQLFluff

on:
  pull_request:
    branches: [main, stg, dev]
    paths:
      - '**.sql'

jobs:

  sqlfluff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install SQLFluff
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade sqlfluff

    - name: Lint using SQLFluff
      run: |
        sqlfluff lint --config=.sqlfluff
